name: Amazon Clone
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://dinesh-amazon-clone1 --delete

    - name: List files in S3 bucket
      run: aws s3 ls s3://dinesh-amazon-clone1 --recursive

    - name: Download specific artifact from S3
      run: aws s3 cp s3://dinesh-amazon-clone1/path/to/your/artifact ./local-artifact-location
