name: Amazon Clone

on:
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    run-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://amazonclone8890 --delete
      
    
